title: Tiyler Gratz
#logo:
#description: text below logo
#show_downlaods: true
theme: jekyll-theme-cayman

navigation: 
- title: "About Me"
url: "/"
- title: "Projects"
url: "projects"
- title: "Art"
url: "art"
- title: "Resume"
url: "resume"
