title: Tiyler Gratz
#logo:
#description: text below logo
#show_downlaods: true
theme: mmistakes/minimal-mistakes

navigation: 
  - title: "About Me"
    url: "/"
  - title: "Projects"
    url: "projects"
  - title: "Art"
    url: "art"
  - title: "Resume"
    url: "resume"
